-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
-- at: site: type:
-- 2023-10-15 17:35:32 EDT Oracle Database 11g
-- Oracle Database 11g
-- predefined type, no DDL - MDSYS.SDO_GEOMETRY predefined type, no DDL - XMLTYPE
CREATE TABLE csy_cc (
courcustid INTEGER NOT NULL,
dateofdel DATE NOT NULL );
COMMENT ON COLUMN csy_cc.courcustid IS
'unique identifier for each courier-customer record in this table.';
COMMENT ON COLUMN csy_cc.dateofdel IS 'date and time of the delivery';
ALTER TABLE csy_cc ADD CONSTRAINT csy_cc_pk PRIMARY KEY ( courcustid ); CREATE TABLE csy_courier (
courierid
name
age
homeaddress
phonenumber
vehicletype
plateno
gender
bankaccno
bankroutingno csy_cc_courcustid INTEGER, csy_del_orderid INTEGER
);
COMMENT ON COLUMN csy_courier.courierid IS ' Unique identifier for each courier';
COMMENT ON COLUMN csy_courier.name IS
INTEGER NOT NULL,
VARCHAR2(255) NOT NULL, INTEGER NOT NULL,
VARCHAR2(500) NOT NULL, VARCHAR2(15) NOT NULL,
VARCHAR2(50) NOT NULL, VARCHAR2(20),
VARCHAR2(30), VARCHAR2(20) NOT NULL,
VARCHAR2(9) NOT NULL,
 ' Full name of the courier';
COMMENT ON COLUMN csy_courier.age IS 'Age of the courier';
COMMENT ON COLUMN csy_courier.homeaddress IS 'Residential address of the courier';
COMMENT ON COLUMN csy_courier.phonenumber IS 'Contact number for the courier';
COMMENT ON COLUMN csy_courier.vehicletype IS 'The mode of transport the courier uses for deliveries';
COMMENT ON COLUMN csy_courier.plateno IS
' Registration number of the courier''s vehicle (if applicable).';
COMMENT ON COLUMN csy_courier.gender IS
'Gender specification for the courier - Male, Female, Non-binary etc.';
COMMENT ON COLUMN csy_courier.bankaccno IS
' Banking detail for processing payments to the courie';
COMMENT ON COLUMN csy_courier.bankroutingno IS 'Banking routing number for payment processing';
ALTER TABLE csy_courier ADD CONSTRAINT csy_courier_pk PRIMARY KEY ( courierid ); CREATE TABLE csy_cust (
customerid
name
age
homeaddress
phoneno
emailaddress
customertype csy_cc_courcustid INTEGER, csy_del_orderid INTEGER
);
COMMENT ON COLUMN csy_cust.customerid IS 'Unique identifier for each customer.';
COMMENT ON COLUMN csy_cust.name IS
INTEGER NOT NULL, VARCHAR2(255) NOT NULL,
INTEGER NOT NULL, VARCHAR2(500) NOT NULL,
VARCHAR2(15) NOT NULL, VARCHAR2(255) NOT NULL, VARCHAR2(50) NOT NULL,

 ' Full name of the customer';
COMMENT ON COLUMN csy_cust.age IS ' Age of the customer.';
COMMENT ON COLUMN csy_cust.homeaddress IS 'Delivery or billing address of the customer';
COMMENT ON COLUMN csy_cust.phoneno IS ' Contact number for the customer';
COMMENT ON COLUMN csy_cust.emailaddress IS
'Email address for order confirmations and notifications.';
COMMENT ON COLUMN csy_cust.customertype IS
' Specifies if the customer is an individual or a corporate entity';
ALTER TABLE csy_cust ADD CONSTRAINT csy_cust_pk PRIMARY KEY ( customerid );
CREATE TABLE csy_del (
orderid INTEGER NOT NULL,
);
orddatetime
deldatetime
amount
paymentmethod VARCHAR2(50) NOT NULL, tips NUMBER(6, 2),
cardno cardname expiry
cvv
VARCHAR2(20) NOT NULL, VARCHAR2(255) NOT NULL,
DATE NOT NULL, INTEGER NOT NULL
DATE NOT NULL, DATE NOT NULL,
NUMBER(10, 2) NOT NULL,
COMMENT ON COLUMN csy_del.orderid IS 'Unique identifier for each order/delivery';
COMMENT ON COLUMN csy_del.orddatetime IS 'When the customer placed the order.';
COMMENT ON COLUMN csy_del.deldatetime IS ' Expected or actual delivery time.';
COMMENT ON COLUMN csy_del.amount IS 'Total cost of the order';

 COMMENT ON COLUMN csy_del.paymentmethod IS 'Method chosen for payment (e.g., credit card)';
COMMENT ON COLUMN csy_del.tips IS 'Gratuity given by the customer';
COMMENT ON COLUMN csy_del.cardno IS 'Credit/Debit card number used for payment.';
COMMENT ON COLUMN csy_del.cardname IS 'Name as it appears on the credit/debit card.';
COMMENT ON COLUMN csy_del.expiry IS 'Expiry date of the credit/debit card.';
COMMENT ON COLUMN csy_del.cvv IS
' Card verification value for the credit/debit card.';
ALTER TABLE csy_del ADD CONSTRAINT csy_del_pk PRIMARY KEY ( orderid ); CREATE TABLE csy_rest (
restid
restname
restadd
restpno
weburl
specialty
csy_del_orderid INTEGER
INTEGER NOT NULL, VARCHAR2(255) NOT NULL,
VARCHAR2(500) NOT NULL, VARCHAR2(15) NOT NULL,
VARCHAR2(255), VARCHAR2(100) NOT NULL,
);
COMMENT ON COLUMN csy_rest.restid IS 'Unique identifier for each restaurant';
COMMENT ON COLUMN csy_rest.restname IS 'Name of the Restaurant';
COMMENT ON COLUMN csy_rest.restadd IS 'Physical location of the restaurant';
COMMENT ON COLUMN csy_rest.restpno IS ' Contact number for the restaurant';
COMMENT ON COLUMN csy_rest.weburl IS
' Online website of the restaurant (if they have one)';

 COMMENT ON COLUMN csy_rest.specialty IS
' Cuisine type or Specialty such as Indian Food, Mexican Food, Chinese Food, Italian Food,
Fast Food, Oriental Food, American Food, Continental Food etc.' ;
ALTER TABLE csy_rest ADD CONSTRAINT csy_rest_pk PRIMARY KEY ( restid );
ALTER TABLE csy_courier
ADD CONSTRAINT csy_courier_csy_cc_fk FOREIGN KEY ( csy_cc_courcustid )
REFERENCES csy_cc ( courcustid );
ALTER TABLE csy_courier
ADD CONSTRAINT csy_courier_csy_del_fk FOREIGN KEY ( csy_del_orderid )
REFERENCES csy_del ( orderid );
ALTER TABLE csy_cust
ADD CONSTRAINT csy_cust_csy_cc_fk FOREIGN KEY ( csy_cc_courcustid )
REFERENCES csy_cc ( courcustid );
ALTER TABLE csy_cust
ADD CONSTRAINT csy_cust_csy_del_fk FOREIGN KEY ( csy_del_orderid )
REFERENCES csy_del ( orderid );
ALTER TABLE csy_rest
ADD CONSTRAINT csy_rest_csy_del_fk FOREIGN KEY ( csy_del_orderid )
REFERENCES csy_del ( orderid );
-- Oracle SQL Developer Data Modeler Summary Report: --
-- CREATE TABLE
-- CREATE INDEX
-- ALTER TABLE
-- CREATE VIEW
-- ALTER VIEW
-- CREATE PACKAGE
-- CREATE PACKAGE BODY
-- CREATE PROCEDURE
-- CREATE FUNCTION
-- CREATE TRIGGER
-- ALTER TRIGGER
-- CREATE COLLECTION TYPE
-- CREATE STRUCTURED TYPE
-- CREATE STRUCTURED TYPE BODY
-- CREATE CLUSTER
-- CREATE CONTEXT
-- CREATE DATABASE
-- CREATE DIMENSION
-- CREATE DIRECTORY
-- CREATE DISK GROUP
-- CREATE ROLE
-- CREATE ROLLBACK SEGMENT
-- CREATE SEQUENCE
-- CREATE MATERIALIZED VIEW
-- CREATE MATERIALIZED VIEW LOG
-- CREATE SYNONYM
-- CREATE TABLESPACE
-- CREATE USER --
-- DROP TABLESPACE
-- DROP DATABASE --
-- REDACTION POLICY --
-- ORDS DROP SCHEMA
-- ORDS ENABLE SCHEMA
-- ORDS ENABLE OBJECT --
-- ERRORS
-- WARNINGS
