-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
-- at:
-- site: -- type:
-- predefined type, no DDL - MDSYS.SDO_GEOMETRY -- predefined type, no DDL - XMLTYPE
CREATE TABLE csy_sf (
);
facilityid
elevator
elevatorcount
escalator
escalatorcount
restroom
wheelchairaccessible CHAR(1) NOT NULL, transferconnection CHAR(1) NOT NULL, transferconnectioncount INTEGER,
busconnection "24HourBooth" csy_ss_stationid
CHAR(1) NOT NULL, CHAR(1) NOT NULL, INTEGER NOT NULL
INTEGER NOT NULL, CHAR(1) NOT NULL,
INTEGER DEFAULT 0, CHAR(1) NOT NULL,
INTEGER DEFAULT 0, CHAR(1) NOT NULL,
ALTER TABLE csy_sf
ADD CHECK ( elevator IN ( 'N', 'Y' ) );
ALTER TABLE csy_sf
ADD CHECK ( escalator IN ( 'N', 'Y' ) );
ALTER TABLE csy_sf
ADD CHECK ( restroom IN ( 'N', 'Y' ) );
ALTER TABLE csy_sf
ADD CHECK ( wheelchairaccessible IN ( 'N', 'Y' ) );
ALTER TABLE csy_sf
 ADD CHECK ( transferconnection IN ( 'N', 'Y' ) );
ALTER TABLE csy_sf
ADD CHECK ( busconnection IN ( 'N', 'Y' ) );
ALTER TABLE csy_sf
ADD CHECK ( "24HourBooth" IN ( 'N', 'Y' ) );
COMMENT ON COLUMN csy_sf.facilityid IS
'Unique identifier for facility data related to a subway station.';
COMMENT ON COLUMN csy_sf.elevator IS
' Indicator if the station has an elevator (Y for Yes, N for No)';
COMMENT ON COLUMN csy_sf.elevatorcount IS 'Number of elevators present at the station';
COMMENT ON COLUMN csy_sf.escalator IS
'Indicator if the station has an escalator (Y for Yes, N for No)';
COMMENT ON COLUMN csy_sf.escalatorcount IS 'Number of escalators present at the station.';
COMMENT ON COLUMN csy_sf.restroom IS
'Indicator if the station has restroom facilities (Y for Yes, N for No)';
COMMENT ON COLUMN csy_sf.wheelchairaccessible IS
'Indicator if the station has restroom facilities (Y for Yes, N for No)';
COMMENT ON COLUMN csy_sf.transferconnection IS
' Indicates if transfers to other train lines are available (Y for Yes, N for No)';
COMMENT ON COLUMN csy_sf.transferconnectioncount IS
' Number of different train lines one can transfer to at this station.';
COMMENT ON COLUMN csy_sf.busconnection IS
' Indicates if there''s a bus connection available at or near the station (Y for Yes, N for No)';
COMMENT ON COLUMN csy_sf."24HourBooth" IS
'Indicates if the station has a booth manned 24 hours (Y for Yes, N for No)';
CREATE UNIQUE INDEX csy_sf__idx ON csy_sf (
csy_ss_stationid

 ASC );
ALTER TABLE csy_sf ADD CONSTRAINT csy_sf_pk PRIMARY KEY ( facilityid );
CREATE TABLE csy_sop (
operationid INTEGER NOT NULL, arrivaldatetime TIMESTAMP, departuredatetime TIMESTAMP,
type VARCHAR2(20) NOT NULL
);
ALTER TABLE csy_sop
ADD CHECK ( type IN ( 'express', 'local', 'mixed' ) );
COMMENT ON COLUMN csy_sop.operationid IS
'Unique identifier for each recorded operation or event.';
COMMENT ON COLUMN csy_sop.arrivaldatetime IS 'Timestamp when the train arrives at the station';
COMMENT ON COLUMN csy_sop.departuredatetime IS 'Timestamp when the train departs from the station.';
COMMENT ON COLUMN csy_sop.type IS
'Type of operation/service (e.g., local, express, or mixed service)';
ALTER TABLE csy_sop ADD CONSTRAINT csy_sop_pk PRIMARY KEY ( operationid ); CREATE TABLE csy_ss (
stationid
stationname
stationaddress
borough
neighborhood
csy_trss_trss_id INTEGER, csy_sop_operationid INTEGER
INTEGER NOT NULL, VARCHAR2(50) NOT NULL,
VARCHAR2(100) NOT NULL, VARCHAR2(50) NOT NULL,
VARCHAR2(50) NOT NULL,
);
COMMENT ON COLUMN csy_ss.stationid IS ' Unique identifier for each subway station.';
COMMENT ON COLUMN csy_ss.stationname IS 'Common name of the subway station.';

 COMMENT ON COLUMN csy_ss.stationaddress IS
'Street or location-based address for the subway station.';
COMMENT ON COLUMN csy_ss.borough IS
'The main borough (e.g., Manhattan, Brooklyn) in which the station is located';
COMMENT ON COLUMN csy_ss.neighborhood IS
'More specific locale or neighborhood where the station is situated';
ALTER TABLE csy_ss ADD CONSTRAINT csy_ss_pk PRIMARY KEY ( stationid ); CREATE TABLE csy_tr (
trainlineid
linenumber
linename
division
yearsinoperation INTEGER NOT NULL, csy_trss_trss_id INTEGER, csy_sop_operationid INTEGER
);
COMMENT ON COLUMN csy_tr.trainlineid IS 'Unique identifier for each train line.';
COMMENT ON COLUMN csy_tr.linenumber IS
'Symbolic representation of the train line (could be a number or letter)';
COMMENT ON COLUMN csy_tr.linename IS
'Descriptive name of the train line, often indicative of its route or main avenue';
COMMENT ON COLUMN csy_tr.division IS
'Denotes which division or group the train line belongs to (e.g., IND, BMT)';
COMMENT ON COLUMN csy_tr.yearsinoperation IS
'The total number of years this train line has been in service';
ALTER TABLE csy_tr ADD CONSTRAINT csy_tr_pk PRIMARY KEY ( trainlineid );
CREATE TABLE csy_trss ( trss_id INTEGER NOT NULL
);
COMMENT ON COLUMN csy_trss.trss_id IS
'Unique identifier for each pairing of train line and subway station.';
INTEGER NOT NULL, VARCHAR2(3) NOT NULL,
VARCHAR2(50) NOT NULL, VARCHAR2(3) NOT NULL,

 ALTER TABLE csy_trss ADD CONSTRAINT csy_trss_pk PRIMARY KEY ( trss_id );
ALTER TABLE csy_sf
ADD CONSTRAINT csy_sf_csy_ss_fk FOREIGN KEY ( csy_ss_stationid )
REFERENCES csy_ss ( stationid );
ALTER TABLE csy_ss
ADD CONSTRAINT csy_ss_csy_sop_fk FOREIGN KEY ( csy_sop_operationid )
REFERENCES csy_sop ( operationid );
ALTER TABLE csy_ss
ADD CONSTRAINT csy_ss_csy_trss_fk FOREIGN KEY ( csy_trss_trss_id )
REFERENCES csy_trss ( trss_id );
ALTER TABLE csy_tr
ADD CONSTRAINT csy_tr_csy_sop_fk FOREIGN KEY ( csy_sop_operationid )
REFERENCES csy_sop ( operationid );
ALTER TABLE csy_tr
ADD CONSTRAINT csy_tr_csy_trss_fk FOREIGN KEY ( csy_trss_trss_id )
REFERENCES csy_trss ( trss_id );
-- Oracle SQL Developer Data Modeler Summary Report: --
-- CREATE TABLE
-- CREATE INDEX
-- ALTER TABLE
-- CREATE VIEW
-- ALTER VIEW
5
1 18 0
0
0
0 0
0 0
0
0
0
-- CREATE PACKAGE
-- CREATE PACKAGE BODY
-- CREATE PROCEDURE
-- CREATE FUNCTION
-- CREATE TRIGGER
-- ALTER TRIGGER
-- CREATE COLLECTION TYPE
-- CREATE STRUCTURED TYPE
-- CREATE STRUCTURED TYPE BODY
-- CREATE CLUSTER 0
-- CREATE CONTEXT 0
-- CREATE DATABASE 0
0

-- CREATE DIMENSION
-- CREATE DIRECTORY
-- CREATE DISK GROUP
-- CREATE ROLE
0 0
0 0
-- CREATE ROLLBACK SEGMENT
-- CREATE SEQUENCE
-- CREATE MATERIALIZED VIEW
-- CREATE MATERIALIZED VIEW LOG
-- CREATE SYNONYM
0 0
0
-- CREATE TABLESPACE
-- CREATE USER --
-- DROP TABLESPACE
-- DROP DATABASE --
-- REDACTION POLICY --
-- ORDS DROP SCHEMA
-- ORDS ENABLE SCHEMA
-- ORDS ENABLE OBJECT --
-- ERRORS
-- WARNINGS
